<DashboardScreen>:
    BoxLayout:
        orientation: "horizontal"

        # MENU LATERAL
        BoxLayout:
            size_hint_x: 0.2
            orientation: "vertical"
            padding: 10
            spacing: 10
            canvas.before:
                Color:
                    rgb: .1,.1,.1
                Rectangle:
                    pos: self.pos
                    size: self.size

            Label:
                text: "ERP"
                font_size: 22
                size_hint_y: None
                height: 60

            Button:
                text: "Empleados"
                on_press: root.manager.current = "empleados"

        # AREA CENTRAL
        BoxLayout:
            Label:
                text: "DASHBOARD"
                font_size: 30
